services:

  postgres:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  webapi:
    #image: ghcr.io/rpry/otus_webapi:1.0
    image: webapi
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "http://+:5100"
      "RMQSettings:Host": "rabbitmqhost"
      "RMQSettings:VHost": "/"
      "RMQSettings:Login": "guest"
      "RMQSettings:Password": "guest"
      "ConnectionString2": "Host=postgres;Port=5432;Database=otus;UserId=postgres;Password=password"
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - "5101:5100"               
 
volumes:
  rabbitmq_data:
  pg-data:
  pg-admin: 
 
networks:
  default:
    name: myLocalNetwork # создана извне: docker network create --driver=bridge myLocalNetwork
    external: true