services:
  
  #Database
  postgres:
    container_name: 'promocode-postgres'
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: otus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  #Webapi    
  promocode-webapi:
    container_name: 'promocode-webapi'
    image: webapi
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "http://+:5100"
      "ConnectionString": "Host=postgres;Port=5432;Database=otus;UserId=postgres;Password=password"
    build:
      context: src
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5101:5100"
    depends_on: 
      - postgres                 
 
volumes:
  rabbitmq_data:
  pg-data:
  pg-admin: 
 
networks:
  default:
    name: myLocalNetwork # создана извне: docker network create --driver=bridge myLocalNetwork
    external: true